Map<String, String> airlineData = {
  
  "AA": "American Airlines",
  "DL": "Delta Air Lines",
  "UA": "United Airlines",
  "WN": "Southwest Airlines",
  "BA": "British Airways",
  "AF": "Air France",
  "LH": "Lufthansa",
  "EK": "Emirates",
  "SQ": "Singapore Airlines",
  "QF": "Qantas",
  "CX": "Cathay Pacific",
  "NH": "All Nippon Airways",
  "JL": "Japan Airlines",
  "KL": "KLM Royal Dutch Airlines",
  "IB": "Iberia",
  "AZ": "Alitalia",
  "VA": "Virgin Australia",
  "NZ": "Air New Zealand",
  "AC": "Air Canada",
  "FR": "Ryanair",
  "U2": "EasyJet",
  "LX": "Swiss International Air Lines",
  "SK": "Scandinavian Airlines",
  "AY": "Finnair",
  "TK": "Turkish Airlines",
  "QR": "Qatar Airways",
  "EY": "Etihad Airways",
  "MH": "Malaysia Airlines",
  "GA": "Garuda Indonesia",
  "QZ": "Indonesia AirAsia",
  "AK": "AirAsia",
  "KE": "Korean Air",
  "OZ": "Asiana Airlines",
  "CI": "China Airlines",
  "BR": "EVA Air",
  "MU": "China Eastern Airlines",
  "CZ": "China Southern Airlines",
  "CA": "Air China",
  "HU": "Hainan Airlines",
  "MF": "XiamenAir",
  "ZH": "Shenzhen Airlines",
  "3U": "Sichuan Airlines",
  "9C": "Spring Airlines",
  "HO": "Juneyao Airlines",
  "FM": "Shanghai Airlines",
  "SC": "Shandong Airlines",
  "JD": "Capital Airlines",
  "G5": "China Express Airlines",
  "8L": "Lucky Air",
  "PN": "West Air",
  "KN": "China United Airlines",
  "GS": "Tianjin Airlines",
  "TV": "Tibet Airlines",
  "KY": "Kunming Airlines",
  "DZ": "Donghai Airlines",
  "QW": "Qingdao Airlines",
  "GX": "Guangxi Beibu Gulf Airlines",
  "RY": "Jiangxi Air",
  "NS": "Hebei Airlines",
  "DR": "Ruili Airlines",
  "EU": "Chengdu Airlines",
  "BK": "Okay Airways",
  "8Y": "Suparna Airlines",
  "Y8": "Yangtze River Express",
  "IJ": "Spring Japan",
  "MM": "Peach Aviation",
  "JW": "Vanilla Air",
  "GK": "Jetstar Japan",
  "LQ": "Lanmei Airlines",
  "QD": "JC International Airlines",
  "ZA": "Sky Angkor Airlines",
  "KR": "Cambodia Airways",
  "K6": "Cambodia Angkor Air",
  "PG": "Bangkok Airways",
  "FD": "Thai AirAsia",
  "SL": "Thai Lion Air",
  "WE": "Thai Smile",
  "DD": "Nok Air",
  "VZ": "Thai Vietjet Air",
  "VJ": "VietJet Air",
  "VN": "Vietnam Airlines",
  "BL": "Bamboo Airways",
  "QH": "AirAsia Vietnam",
  "QV": "Lao Airlines",
  "MK": "Air Mauritius",
  "UU": "Air Austral",
  "HM": "Air Seychelles",
  "KQ": "Kenya Airways",
  "ET": "Ethiopian Airlines",
  "MS": "EgyptAir",
  "AT": "Royal Air Maroc",
  "AH": "Air Algérie",
  "TU": "Tunisair",
  "SA": "South African Airways",
  "4Z": "Airlink",
  "MN": "Comair",
  "VS": "Virgin Atlantic",
  "LS": "Jet2.com",
  "BE": "Flybe",
  "EI": "Aer Lingus",
  "EW": "Eurowings",
  "4U": "Germanwings",
  "AB": "Air Berlin",
  "HG": "Niki",
  "UX": "Air Europa",
  "VY": "Vueling",
  "TP": "TAP Air Portugal",
  "PS": "Ukraine International Airlines",
  "LO": "LOT Polish Airlines",
  "OK": "Czech Airlines",
  "RO": "TAROM",
  "MA": "Malev",
  "JU": "Air Serbia",
  "YM": "Montenegro Airlines",
  "JP": "Adria Airways",
  "BT": "Air Baltic",
  "OV": "Estonian Air",
  "DY": "Norwegian Air Shuttle",
  "WF": "Widerøe",
  "FI": "Icelandair",
  "WW": "WOW air"
};
Map<String, String> airportData = {
  "SYD": "Sydney Kingsford Smith Airport",
  "MEL": "Melbourne Airport",
  "BNE": "Brisbane Airport",
  "PER": "Perth Airport",
  "ADL": "Adelaide Airport",
  "CBR": "Canberra Airport",
  "OOL": "Gold Coast Airport",
  "HBA": "Hobart International Airport",
  "DRW": "Darwin International Airport",
  "CNS": "Cairns Airport",
  "AKL": "Auckland Airport",
  "WLG": "Wellington Airport",
  "CHC": "Christchurch Airport",
  "ZQN": "Queenstown Airport",
  "NAN": "Nadi International Airport",
  "PPT": "Faa'a International Airport",
  "RAR": "Rarotonga International Airport",
  "APW": "Faleolo International Airport",
  "TBU": "Fuaʻamotu International Airport",
  "VLI": "Bauerfield International Airport",
  "INU": "Nauru International Airport",
  "FUN": "Funafuti International Airport",
  "TRW": "Bonriki International Airport",
  "CXI": "Cassidy International Airport",
  "TAR": "Tarawa International Airport",
  "ATL": "Hartsfield-Jackson Atlanta International Airport",
  "PEK": "Beijing Capital International Airport",
  "LAX": "Los Angeles International Airport",
  "DXB": "Dubai International Airport",
  "HND": "Tokyo Haneda Airport",
  "ORD": "O'Hare International Airport",
  "LHR": "London Heathrow Airport",
  "HKG": "Hong Kong International Airport",
  "PVG": "Shanghai Pudong International Airport",
  "CDG": "Charles de Gaulle Airport",
  "DFW": "Dallas/Fort Worth International Airport",
  "AMS": "Amsterdam Airport Schiphol",
  "FRA": "Frankfurt Airport",
  "IST": "Istanbul Airport",
  "CAN": "Guangzhou Baiyun International Airport",
  "JFK": "John F. Kennedy International Airport",
  "SIN": "Singapore Changi Airport",
  "ICN": "Incheon International Airport",
  "DEN": "Denver International Airport",
  "BKK": "Suvarnabhumi Airport",
  "MIA": "Miami International Airport",
  "GRU": "São Paulo-Guarulhos International Airport",
  "SEA": "Seattle-Tacoma International Airport",
  "MUC": "Munich Airport",
  "MEX": "Mexico City International Airport",
  "BCN": "Barcelona-El Prat Airport",
  "YYZ": "Toronto Pearson International Airport",
  "SFO": "San Francisco International Airport",
  "EZE": "Ministro Pistarini International Airport",
  "ZRH": "Zurich Airport",
  "BOM": "Chhatrapati Shivaji Maharaj International Airport",
  "JNB": "O.R. Tambo International Airport",
  "MAD": "Adolfo Suárez Madrid-Barajas Airport",
  "DME": "Domodedovo International Airport",
  "FCO": "Leonardo da Vinci–Fiumicino Airport",
  "GIG": "Rio de Janeiro-Galeão International Airport",
  "BOS": "Logan International Airport",
  "MNL": "Ninoy Aquino International Airport",
  "KUL": "Kuala Lumpur International Airport",
  "DEL": "Indira Gandhi International Airport",
  "CPT": "Cape Town International Airport",
  "DUB": "Dublin Airport",
  "VIE": "Vienna International Airport",
  "OSL": "Oslo Gardermoen Airport",
  "ARN": "Stockholm Arlanda Airport",
  "HEL": "Helsinki-Vantaa Airport",
  "CPH": "Copenhagen Airport",
  "BRU": "Brussels Airport",
  "GVA": "Geneva Airport",
  "WAW": "Warsaw Chopin Airport",
  "PRG": "Václav Havel Airport Prague",
  "BUD": "Budapest Ferenc Liszt International Airport",
  "ATH": "Athens International Airport",
  "LIS": "Humberto Delgado Airport",
  "OTP": "Henri Coandă International Airport",
  "SOF": "Sofia Airport",
  "BEG": "Belgrade Nikola Tesla Airport",
  "LED": "Pulkovo Airport",
  "SVO": "Sheremetyevo International Airport",
  "VKO": "Vnukovo International Airport",
  "SCL": "Comodoro Arturo Merino Benítez International Airport",
  "LIM": "Jorge Chávez International Airport",
  "UIO": "Mariscal Sucre International Airport",
  "GYE": "José Joaquín de Olmedo International Airport",
  "MDE": "José María Córdova International Airport",
  "PTY": "Tocumen International Airport",
  "HAV": "José Martí International Airport",
  "SDQ": "Las Américas International Airport",
  "SJU": "Luis Muñoz Marín International Airport",
  "KIN": "Norman Manley International Airport",
  "MBJ": "Sangster International Airport",
  "NAS": "Lynden Pindling International Airport",
  "POS": "Piarco International Airport",
  "CUN": "Cancún International Airport",
  "SJD": "Los Cabos International Airport",
  "PVR": "Licenciado Gustavo Díaz Ordaz International Airport",
  "GDL": "Guadalajara International Airport",
  "MTY": "Monterrey International Airport",
  "TIJ": "Tijuana International Airport",
  "HMO": "Hermosillo International Airport",
  "CUL": "Culiacán International Airport",
  "MZT": "Mazatlán International Airport",
  "ZIH": "Ixtapa-Zihuatanejo International Airport",
  "VER": "Veracruz International Airport",
  "MID": "Mérida International Airport",
  "CZM": "Cozumel International Airport",
  "QRO": "Querétaro Intercontinental Airport",
  "SLP": "Ponciano Arriaga International Airport",
  "TAM": "General Francisco Javier Mina International Airport",
  "VSA": "Carlos Rovirosa Pérez International Airport",
  "REX": "General Lucio Blanco International Airport",
  "TGZ": "Ángel Albino Corzo International Airport",
  "MLM": "General Francisco J. Mujica International Airport",
  "PBC": "Hermanos Serdán International Airport",
  "OAX": "Xoxocotlán International Airport",
  "CPE": "Ingeniero Alberto Acuña Ongay International Airport",
  "CME": "Ciudad del Carmen International Airport",
  "CJS": "Abraham González International Airport",
  "CUU": "General Roberto Fierro Villalobos International Airport",
  "DGO": "General Guadalupe Victoria International Airport",
  "AGU": "Lic. Jesús Terán Peredo International Airport",
  "ZCL": "General Leobardo C. Ruiz International Airport",
  "LAP": "Manuel Márquez de León International Airport",
  "LTO": "Loreto International Airport",
  "MAM": "General Servando Canales International Airport",
  "PQM": "Palenque International Airport",
  "TLC": "Licenciado Adolfo López Mateos International Airport",
  "UPN": "Lic. y Gen. Ignacio López Rayón International Airport",
  "ZLO": "Playa de Oro International Airport",
  "CLQ": "Licenciado Miguel de la Madrid Airport",
  "TPQ": "Amado Nervo National Airport",
  "HUX": "Bahías de Huatulco International Airport",
  "ISJ": "Isla Mujeres National Airport",
  "ACA": "General Juan N. Álvarez International Airport",
  "MGA": "Augusto C. Sandino International Airport",
  "SAL": "El Salvador International Airport",
  "SAP": "Ramón Villeda Morales International Airport",
  "TGU": "Toncontín International Airport",
  "GUA": "La Aurora International Airport",
  "BZE": "Philip S. W. Goldson International Airport",
  "SJO": "Juan Santamaría International Airport",
  "LIR": "Daniel Oduber Quirós International Airport",
  "BOG": "El Dorado International Airport",
  "CTG": "Rafael Núñez International Airport",
  "CLO": "Alfonso Bonilla Aragón International Airport",
  "BSB": "Brasília International Airport",
  "SSA": "Deputado Luís Eduardo Magalhães International Airport",
  "FOR": "Pinto Martins – Fortaleza International Airport",
  "REC": "Recife/Guararapes–Gilberto Freyre International Airport",
  "CWB": "Afonso Pena International Airport",
  "POA": "Salgado Filho International Airport",
  "BEL": "Val de Cans International Airport",
  "MAO": "Eduardo Gomes International Airport",
  "VCP": "Viracopos International Airport",
  "PHL": "Philadelphia International Airport",
  "PHX": "Phoenix Sky Harbor International Airport",
  "IAH": "George Bush Intercontinental Airport",
  "MCO": "Orlando International Airport",
  "LAS": "McCarran International Airport",
  "CLT": "Charlotte Douglas International Airport",
  "FLL": "Fort Lauderdale-Hollywood International Airport",
  "MSP": "Minneapolis-Saint Paul International Airport",
  "DTW": "Detroit Metropolitan Airport",
  "BWI": "Baltimore/Washington International Thurgood Marshall Airport",
  "SLC": "Salt Lake City International Airport",
  "SAN": "San Diego International Airport",
  "TPA": "Tampa International Airport",
  "PDX": "Portland International Airport",
  "HNL": "Daniel K.",
};
